version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: pg-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clarifield
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
